### **`Problem-1:`** Write a Python function that takes a list and returns a new list with unique elements of the first list.

**Exercise 1:**

Input:

```bash
[1,2,3,3,3,3,4,5]
```

Output:

```bash
[1, 2, 3, 4, 5]
```

In [ ]:
def unique(List):
    """
    This function get list of number and return unique numbers
    input:list of numbers
    output:unique elements in the list
    """
    set1=set(List)
    set1=list(set1)
    return set1
L=[1,2,3,3,3,3,4,5]
print(unique(L))

[1, 2, 3, 4, 5]

### **`Problem-2:`** Write a Python function that accepts a hyphen-separated sequence of words as parameter and returns the words in a hyphen-separated sequence after sorting them alphabetically.

**Example 1:**

Input:
```bash
green-red-yellow-black-white
```

Output:
```bash
black-green-red-white-yellow
```

In [ ]:
# Write code here
def sort_fun(l):
    """
    The sort_fun() function accept a string hypen separated values
    and convert into sorted form and return
    input:unsorted hypen text
    output:sorted hypen text
    """
    newtext=l.split('-')
    newtext.sort()
    newtext='-'.join(newtext)
    return newtext

str1="green-red-yellow-black-white"
print(sort_fun(str1))

black-green-red-white-yellow

### **`Problem 3:`** Write a Python function that accepts a string and calculate the number of upper case letters and lower case letters.

```
Sample String : 'CampusX is an Online Mentorship Program fOr EnginEering studentS.'
Expected Output :
No. of Upper case characters :  9
No. of Lower case Characters :  47
```

In [ ]:
# Write code here
def letter_counter(str1):
    """
    This function accept a string and counts how many upper or lower letter in a string
    input:string
    output:count of upper and lower string
    """
    small=0
    large=0
    for char in str1:
        if char.isupper():
            large+=1
        if char.islower():
            small+=1
    return f"No. of Upper case characters : {large}\nNo. of Lower case Characters : {small}"
    k=str1
s="CampusX is an Online Mentorship Program fOr EnginEering studentS"
print(letter_counter(s))

No. of Upper case characters : 9
No. of Lower case Characters : 47

### **`Problem 4:`** Write a Python program to print the even numbers from a given list.
```
Sample List : [1, 2, 3, 4, 5, 6, 7, 8, 9]
Expected Result : [2, 4, 6, 8]
```

In [ ]:
# Write code here
L=[1, 2, 3, 4, 5, 6, 7, 8, 9]
result=[i for i in L if i%2==0]
print('result :',result)

result : [2, 4, 6, 8]

### **`Problem 5:`** Write a Python function to check whether a number is perfect or not.

A Perfect number is a number that is half the sum of all of its positive divisors (including itself).

Example :

```
The first perfect number is 6, because 1, 2, and 3 are its proper positive divisors, and 1 + 2 + 3 = 6.
Equivalently, the number 6 is equal to half the sum of all its positive divisors: ( 1 + 2 + 3 + 6 ) / 2 = 6.

The next perfect number is 28 = 1 + 2 + 4 + 7 + 14. This is followed by the perfect numbers 496 and 8128.
```

In [ ]:
# Write code here
def is_perfect(num):
    """
    this function accept input number and check number is perfect or not
    input:number (integer)
    output:perfect or not perfect
    """
    l=[]
    for i in range(1,(num//2)+1):
        if num%i==0:
            l.append(i)
    sum=0
    for j in l:
        sum=sum+j
    if (sum+num)/2==num:
        return f"{num} Number is Perfect"
    else:
        return f"{num} Number is not Perfect"

n=496
is_perfect(n)

'496 Number is Perfect'

### **`Problem-6:`** Write a Python function to concatenate any no of dictionaries to create a new one.

```
Sample Dictionary :
dic1={1:10, 2:20}
dic2={3:30, 4:40}
dic3={5:50,6:60}
Expected Result : {1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}
```

In [ ]:
# Write code here
def concatenate_dictionary(list_dict):
    new_dic={}
    for i in list_dict:
        new_dic.update(i)
    return new_dic


dic1={1:10, 2:20}
dic2={3:30, 4:40}
dic3={5:50,6:60}
l=[dic1,dic2,dic3]
print(concatenate_dictionary(l))

{1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}

`Problem-7` Write a python function that accepts a string as input and returns the word with most occurence.

```
Input:
hello how are you i am fine thank you
```

```
Output
you -> 2
```

In [ ]:
# Write code here
def most_occur_char(str1):
    """
    this function accept string our function return most occur word in a string
    input:string
    output:count and word
    """
    new_l=''
    final=''
    count=0
    n=0
    for char in str1:
        if char!=" " and char!=str1[-1]:
            new_l+=char
        else:
            if char==str1[-1]:
                new_l+=char
            n=str1.count(new_l)
            final=new_l
            new_l=""
        if n>count:
            count=n
            final=new_l
            new_l=''
    return f"{final} {n}"
s='hello how are you i am fine thank you'
print(most_occur_char(s))

you 2

`Problem-8` Write a python function that receives a list of integers and prints out a histogram of bin size 10

```
Input:
[13,42,15,37,22,39,41,50]
```

```
Output:
{11-20:2,21-30:1,31-40:2,41-50:3}
```

In [4]:
# Write code here
def histogram(data):
    # Find the minimum and maximum values in the data
    min_value = min(data)
    max_value = max(data)


    # Create a histogram using a dictionary to count occurrences in each bin
    histogram_dict = {}
    for value in data:
        bin_index = (value - min_value) // 10
        bin_start = min_value + bin_index * 10
        if bin_start not in histogram_dict:
            histogram_dict[bin_start] = 1
        else:
            histogram_dict[bin_start] += 1

    # Print the histogram
    print("Histogram:")
    for bin_start, count in sorted(histogram_dict.items()):
        bin_end = bin_start + 9
        print(f"{bin_start}-{bin_end}: {count}")

# Example usage:
data_list = [5, 15, 25, 35, 45, 12, 18, 22, 32, 38, 52, 5, 15, 28, 38]
histogram(data_list)

5
Histogram:
5-14: 3
15-24: 4
25-34: 3
35-44: 3
45-54: 2

`Problem-9` Write a python function that accepts a list of 2D co-ordinates and a query point, and then finds the the co-ordinate which is closest in terms of distance from the query point.

```
List of Coordinates
[(1,1),(2,2),(3,3),(4,4)]
Query Point
(0,0)
```

```
Output
Nearest to (0,0) is (1,1)
```

In [15]:
# Write code here
import math

def find_closest_coordinate(coordinates, query_point):
    if not coordinates:
        return None  # Return None if the list of coordinates is empty

    # Calculate the distance between each coordinate and the query point
    distances = [math.sqrt((x - query_point[0])**2 + (y - query_point[1])**2) for x, y in coordinates]

    # Find the index of the coordinate with the minimum distance
    min_distance_index = distances.index(min(distances))

    # Return the closest coordinate
    return coordinates[min_distance_index]

# Example usage:
coordinate_list = [(1, 1), (2, 2), (3, 3), (4, 4)]
query_point = (0, 0)

closest_coordinate = find_closest_coordinate(coordinate_list, query_point)
print(f"The closest coordinate to {query_point} is: {closest_coordinate}")

The closest coordinate to (0, 0) is: (1, 1)

`Problem-10`:Write a python program that receives a list of strings and performs bag of word operation on those strings

https://en.wikipedia.org/wiki/Bag-of-words_model

In [19]:
# Write code here
# Write code here
def most_occur_char(str1):
    """
    this function accept string our function return most occur word in a string
    input:string
    output:count and word
    """
    new_l=''
    final=''
    n=0
    dic={}
    for char in str1:
        if char!=" ":
            new_l+=char
        else:
            if char==str1[-1]:
                new_l+=char
            n=str1.count(new_l)
            final=new_l
            dic[final]=n
            new_l=""


    return dic
s='hello how are you i am fine thank you hello'
print(most_occur_char(s))

{'hello': 2, 'how': 1, 'are': 1, 'you': 2, 'i': 2, 'am': 1, 'fine': 1, 'thank': 1}

###`Problem 11:` Write a Python program to add three given lists using Python map and lambda.

In [20]:
# Write code here
l1=[3,55,6,7,8,3]
l2=[4,6,2,4,7,8]
l3=[4,6,2,4,7,8]
l4=[l1[i]+l2[i]+l3[i]  for i in range(0,len(l1))]
print(l4)

[11, 67, 10, 15, 22, 19]

###`Problem-12:`Write a Python program to create a list containing the power of said number in bases raised to the corresponding number in the index using Python map.
`Input:`
```
list1 = [1,2,3,4,5,6]
```
`Output:`
```
[1,2,9,64,625,-]
```

In [23]:
# Write code here
list1 = [1,2,3,4,5,6]
s=map(lambda i:i**(i-1) ,list1)
print(list(s))

[1, 2, 9, 64, 625, 7776]

###`Problem-13` Using filter() and list() functions and .lower() method filter all the vowels in a given string.

In [28]:
# Write code here
str1="hey i am Talha siddique from Daska"
vowels = ['a', 'e', 'i', 'o', 'u']
str1=str1.lower()
str1=list(str1)
f=list(filter(lambda v:v in vowels ,str1))
str1=str(str1)
print('Original String :',str1)
print('Change String :',f)

Original String : ['h', 'e', 'y', ' ', 'i', ' ', 'a', 'm', ' ', 't', 'a', 'l', 'h', 'a', ' ', 's', 'i', 'd', 'd', 'i', 'q', 'u', 'e', ' ', 'f', 'r', 'o', 'm', ' ', 'd', 'a', 's', 'k', 'a']
Change String : ['e', 'i', 'a', 'a', 'a', 'i', 'i', 'u', 'e', 'o', 'a', 'a']

`Problem-14`: Use reduce to convert a 2D list to 1D

In [29]:
# Write code here
from functools import reduce

# Example 2D list
two_dimensional_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Use reduce to concatenate sublists into a single list
one_dimensional_list = reduce(lambda x, y: x + y, two_dimensional_list)

print("Original 2D List:")
for row in two_dimensional_list:
    print(row)

print("\nConverted 1D List:", one_dimensional_list)

Original 2D List:
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]

Converted 1D List: [1, 2, 3, 4, 5, 6, 7, 8, 9]

`Problem 15`- A dictionary contains following information about 5 employees:
- First name
- Last name
- Age
- Grade(Skilled,Semi-skilled,Highly skilled)<br>
Write a program using map/filter/reduce to a list of employees(first name + last name) who are highly skilled

In [ ]:
# Write code here
employees = [
    {
        'fname':'Nitish',
        'lname':'Singh',
        'age' : 33,
        'grade':'skilled'
    },
    {
        'fname':'Ankit',
        'lname':'Verma',
        'age' : 34,
        'grade':'semi-skilled'
    },
    {
        'fname':'Neha',
        'lname':'Singh',
        'age' : 35,
        'grade':'highly-skilled'
    },
    {
        'fname':'Anurag',
        'lname':'Kumar',
        'age' : 30,
        'grade':'skilled'
    },
    {
        'fname':'Abhinav',
        'lname':'Sharma',
        'age' : 37,
        'grade':'highly-skilled'
    }

]

In [ ]:
list(map(lambda x:x['fname'] + ' ' + x['lname'],list(filter(lambda x:True if x['grade'] == 'highly-skilled' else False,employees))))

['Neha Singh', 'Abhinav Sharma']